3NET_EventManagement/3NET_EventManagement/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace _3NET_EventManagement.Models
{
    public class Event
    {
        

        [HiddenInput(DisplayValue = false)]
        [Key]
        public int Id { get; set; }

        [Display(Name = "Event name")]
        public string EventName { get; set; }

        [Display(Name = "Event location")]
        public string Address { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd hh:mm tt}")]
        public DateTime Date { get; set; }

        [Display(Name = "Summary")]
        [DataType(DataType.MultilineText)]
        public string Summary { get; set; }

        // relation one to many
        public int CreatorId { get; set; }
        public virtual User Creator { get; set; }

        // de meme pour le status , un évenement a un status et un type
        [Display(Name = "Status")]
        public int StatusId { get; set; }

        public virtual Status Status { get; set; }

        [Display(Name = "Type")]
        public int TypeId { get; set; }

        public virtual EventType Type { get; set; }

        // Un évenement possède plusieurs participants et contributions
        //[Display(Name = "Invited users")]
       // public virtual ICollection<User> InvitedUsers { get; set; }

        public virtual ICollection<Contribution> Contributions { get; set; }

        public virtual ICollection<Invitation> Invitations { get; set; }

        public Event()
        {
           // InvitedUsers = new HashSet<User>();
            Contributions = new HashSet<Contribution>();
            Invitations = new HashSet<Invitation>();
        }
       
    }
}

3NET_EventManagement/3NET_EventManagement/Models/EventType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace _3NET_EventManagement.Models
{
    public class EventType
    {
        [HiddenInput(DisplayValue = false)]
        [Key]
        public int Id { get; set; }

        [Display(Name = "Type")]
        public string TypeName { get; set; }
    }
}

3NET_EventManagement/3NET_EventManagement/Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3NET_EventManagement.Models;
using WebMatrix.WebData;

namespace _3NET_EventManagement.Controllers
{
    public class ContributionController : Controller
    {
        private AppDbContext db = new AppDbContext();

        //
        // GET: /Contribution/EventId

        public ActionResult Index(int id = 0)
        {
            int userId =  WebSecurity.GetUserId(User.Identity.Name);
            var contributions = db.Contributions.Include(c => c.Event).Include(c => c.Type).Where(c => c.EventId == id && c.UserId == userId);
            return View(contributions.ToList());
        }

        //
        // GET: /Contribution/Details/5

        public ActionResult Details(int id = 0)
        {
            Contribution contribution = db.Contributions.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // GET: /Contribution/Create

        public ActionResult Create(int id = 0)
        {
            Event concernedEvent = db.Events.Find(id);
            Contribution contrib = new Contribution();
            contrib.Event = concernedEvent;
            contrib.EventId = concernedEvent.Id;
            contrib.User = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
            contrib.UserId = WebSecurity.GetUserId(User.Identity.Name);
            ViewBag.EventId = new SelectList(db.Events, "Id", "EventName");
            ViewBag.TypeId = new SelectList(db.ContributionTypes, "Id", "ContributionTypeName");
            return View(contrib);
        }

        //
        // POST: /Contribution/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contribution contribution)
        {
            // on set l'utilisateur , l'event et le type concerné
            contribution.User = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
            contribution.Event = db.Events.Find(contribution.EventId);
            contribution.Type = db.ContributionTypes.Find(contribution.TypeId);

            if (contribution.Type != null && contribution.User != null && contribution.Event != null)
            {
                db.Contributions.Add(contribution);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = contribution.EventId });
            }

            ViewBag.EventId = new SelectList(db.Events, "Id", "EventName", contribution.EventId);
            ViewBag.TypeId = new SelectList(db.ContributionTypes, "Id", "ContributionTypeName", contribution.TypeId);
            return View(contribution);
        }

        //
        // GET: /Contribution/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Contribution contribution = db.Contributions.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventId = new SelectList(db.Events, "Id", "EventName", contribution.EventId);
            ViewBag.TypeId = new SelectList(db.ContributionTypes, "Id", "ContributionTypeName", contribution.TypeId);
            return View(contribution);
        }

        //
        // POST: /Contribution/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contribution contribution)
        {
            // on set l'utilisateur , l'event 
            contribution.User = db.Users.Find(contribution.UserId);
            contribution.Event = db.Events.Find(contribution.EventId);
            if (contribution.User != null && contribution.Event != null)
            {
                db.Entry(contribution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = contribution.EventId });
            }
            ViewBag.EventId = new SelectList(db.Events, "Id", "EventName", contribution.EventId);
            ViewBag.TypeId = new SelectList(db.ContributionTypes, "Id", "ContributionTypeName", contribution.TypeId);
            return View(contribution);
        }

        //
        // GET: /Contribution/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Contribution contribution = db.Contributions.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // POST: /Contribution/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contribution contribution = db.Contributions.Find(id);
            db.Contributions.Remove(contribution);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = contribution.EventId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

3NET_EventManagement/3NET_EventManagement/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3NET_EventManagement.Models;
using WebMatrix.WebData;
using System.Web.Security;
using System.Net;

namespace _3NET_EventManagement.Controllers
{
    public class EventController : Controller
    {
        private AppDbContext db = new AppDbContext();

        //
        // GET: /Event/
        public ActionResult Index()
        {
             User user = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
             var events = db.Events.Include(e => e.Status).Include(e => e.Type).ToList();
            // Si l'utilisateur est admin, alors il verra tous les évènements courants
            if (Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
            {
                events = db.Events.Include(e => e.Status).Include(e => e.Type).ToList();
            }
            // Sinon une opération de filtrage s'effectue, selon si on est le créateur de l'event ou si on est invité.
            else 
            {
               // On récupère les events crées par l'utilisateur
               events = db.Events.Include(e => e.Status).Include(e => e.Type).Where( e => e.CreatorId == user.Id).ToList();
                // Si il n'y en a pas on essaye de chercher s'il y a des events ou il est invité
                if (events.ToList().Count == 0)
                {
                   events = db.Events.Include(e => e.Status).Include(e => e.Type).ToList();
                   var eventsTemp = new List<Event>();
                    int count = 0;
                    foreach(var item in events)
                    {
                        foreach(var it2 in item.Invitations)
                        {
                            if ( it2.UserId == user.Id)
                            {
                                count++;
                            }
                        }
                        if(count == 1)
                        {
                            eventsTemp.Add(item);
                            count = 0;
                        }
                    }
                    if (eventsTemp.Count() == 0)
                    {
                        events = new List<Event>();
                       
                    }
                    else
                    {
                        // on ajoute la liste des events ou on est invité si il y en a
                        events = eventsTemp;
                    }
                 

                }
                // Si on possède des events dont on est l'owner, on va ajouter ceux ou on est invité
                else
                {
                    var events3 = db.Events.Include(e => e.Status).Include(e => e.Type).ToList();

                    var eventsTemp = new List<Event>();
                    int count = 0;
                    foreach (var item in events3)
                    {
                        foreach (var it2 in item.Invitations)
                        {
                            if (it2.UserId == user.Id)
                            {
                                count++;
                            }
                        }
                        if (count == 1)
                        {
                            eventsTemp.Add(item);
                            count = 0;
                        }
                    }
                    if (eventsTemp.Count() != 0)
                    {
                      foreach (var item in eventsTemp)
                      {
                          if (events != null)
                          {
                              events.Add(item);
                          }
                          else
                          {
                              events = new List<Event>();
                              events.Add(item);
                          }
                           

                      }

                    }
                }
         
            }
           
            // On set un boolean pour dire l'utilisateur est le owner de l'event pour avoir des droits spécifiques dans l'affichage
            foreach(var item in events)
            {
                if (item.CreatorId == user.Id || Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                {
                    ViewBag.isOwner = true;
                }
                else
                {
                    ViewBag.isOwner = false;
                }
            }
            if (events.ToList().Count == 0)
            {
                ViewData["message"] = "No Event found for the moment.";
            }
            return View(events.ToList());
        }

        //
        // GET: /Event/Details/5

        public ActionResult Details(int id = 0)
        {
            Event @event = db.Events.Find(id);
            foreach ( var item  in @event.Invitations.ToList())
            {
                item.User = db.Users.Find(item.UserId);
                item.Event = db.Events.Find(item.EventId);
            }
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        //
        // GET: /Event/Create

        public ActionResult Create()
        {
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "StatusName");
            ViewBag.TypeId = new SelectList(db.EventTypes, "Id", "TypeName");
            return View();
        }

        //
        // POST: /Event/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event @event)
        {
            User @user = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
        
            
            if (ModelState.IsValid)
            {
                if (Roles.GetRolesForUser(User.Identity.Name).Contains("user"))
                { 
                    @event.StatusId = 2;
                    @event.Creator = @user;
                   // @event.CreatorId = @user.Id;
                    db.Events.Add(@event);
                    db.SaveChanges();
                }
                else
                {
                    @event.CreatorId = @user.Id;
                    db.Events.Add(@event);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
           
                ViewBag.StatusId = new SelectList(db.Statuses, "Id", "StatusName", @event.StatusId);
            
            
            
           
            ViewBag.TypeId = new SelectList(db.EventTypes, "Id", "TypeName", @event.TypeId);
            return View(@event);
        }

        //
        // GET: /Event/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var editedEvent = db.Events.Find(id);
            if (editedEvent == null)
            {
                return HttpNotFound();
            }

            foreach (var item in editedEvent.Invitations.ToList())
            {
                item.User = db.Users.Find(item.UserId);
                item.Event = db.Events.Find(item.EventId);
            }
            
            ViewData["Event"] = editedEvent;
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "StatusName", editedEvent.StatusId);
            ViewBag.TypeId = new SelectList(db.EventTypes, "Id", "TypeName", editedEvent.TypeId);
            return View(editedEvent);
        }

        //
        // POST: /Event/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event editedEvent, FormCollection formAttr)
        {
            if (ModelState.IsValid)
            {

                editedEvent.Creator = db.Users.Find(editedEvent.CreatorId);
                editedEvent.Status = db.Statuses.Find(editedEvent.StatusId);
                editedEvent.Type = db.EventTypes.Find(editedEvent.TypeId);

                db.Entry(editedEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "StatusName", editedEvent.StatusId);
            ViewBag.TypeId = new SelectList(db.EventTypes, "Id", "TypeName", editedEvent.TypeId);
            return View(editedEvent);
        }

        //
        // GET: /Event/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        //
        // POST: /Event/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Include(e => e.Invitations).Include(e => e.Contributions).Where( e => e.Id == id).FirstOrDefault();

            // On vire les invitations et les contributions existantes
            var listOfInvitations   =  db.Invitations.Where(x => x.EventId == id).ToList();
            foreach (var item in listOfInvitations)
                db.Invitations.Remove(item);
            var listOfContributions = db.Contributions.Where(x => x.EventId == id).ToList();
            foreach (var item in listOfContributions)
                db.Contributions.Remove(item);

            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //
        // POST: /Event/LockOrUnLock/5

        //[HttpPost, ActionName("LockOrUnLock")]
       // [ValidateAntiForgeryToken]
        public ActionResult LockOrUnLock(int id)
        {
            // On va changer le status selon le status en cours, Pending => Open, Open => Pending
            Event @event = db.Events.Find(id);
            if (@event.Status.StatusName.Equals("Pending"))

3NET_EventManagement/3NET_EventManagement/Views/Event/Create.cshtml
@model _3NET_EventManagement.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Event</legend>

        <div class="editor-label form_label">
            @Html.LabelFor(model => model.EventName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EventName)
            @Html.ValidationMessageFor(model => model.EventName)
        </div>

        <div class="editor-label form_label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label form_label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label form_label">
            @Html.LabelFor(model => model.Summary)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Summary)
            @Html.ValidationMessageFor(model => model.Summary)
        </div>

        
        @if (Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
{
    <div class="editor-label form_label">
        @Html.LabelFor(model => model.StatusId, "Status")
    </div>
        <div class="editor-field">
            @Html.DropDownList("StatusId", String.Empty)
            @Html.ValidationMessageFor(model => model.StatusId)
        </div>
        }
        <div class="editor-label form_label">
            @Html.LabelFor(model => model.TypeId, "Type")
        </div>
        <div class="editor-field">
            @Html.DropDownList("TypeId", String.Empty)
            @Html.ValidationMessageFor(model => model.TypeId)
        </div>
        <br />
        <p>
            <input type="submit" value="Create" class="btn btn-primary" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

3NET_EventManagement/3NET_EventManagement/Views/Event/Delete.cshtml
@model _3NET_EventManagement.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Event</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EventName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Summary)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Summary)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreatorId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatorId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status.StatusName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status.StatusName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type.TypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type.TypeName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

3NET_EventManagement/3NET_EventManagement/Views/Event/Details.cshtml
@model _3NET_EventManagement.Models.Event

@{
    ViewBag.Title = "Details for event";
}

<h2> @Html.DisplayFor(model => model.EventName) </h2>

<fieldset>
    <legend>Event</legend>
    <ul style="display:inline-flexbox; text-decoration:none; list-style-type:none;">
        <li style="display:inline;"></li>
        <li style="display:inline;"></li>
        <li style="display:inline;"></li>
    </ul>
    <table class="table table-striped">
        <tr class="info">
            <th>
              Type : @Html.DisplayFor(model => model.Type.TypeName)
            </th>
            <th>
               Address :  @Html.DisplayFor(model => model.Address)
            </th>
            <th>
               Creator :  @Html.DisplayFor(model => model.Creator.UserName)
            </th>
            <th>
               Date :  @Html.DisplayFor(model => model.Date)
            </th>
    </table>
            @*<h3>@Html.DisplayNameFor(model => model.EventName)</h3>

                <div class="display-field">

                </div>
                <h3>@Html.DisplayNameFor(model => model.Address)</h3>*@

            @*<div class="display-field">

            </div>

            <h3>@Html.DisplayNameFor(model => model.Date)</h3>
            <div class="display-field">
              
            </div>*@
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Status.StatusName)</dt>
        <dd>@Html.DisplayFor(model => model.Status.StatusName)</dd>
        <dt>@Html.DisplayNameFor(model => model.Summary)</dt>
        <dd>@Html.DisplayFor(model => model.Summary)</dd>
        <dt>Invited Friends</dt>
        <dd><table class="table table-bordered">
    @foreach (var item in Model.Invitations.Where( e => e.EventId == Model.Id).ToList())
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>

        </tr>
    }
</table></dd>
    </dl>
    @*<h3 style="padding-bottom:5px; border-bottom: solid black 1px;" >@Html.DisplayNameFor(model => model.Status.StatusName)</h3>

    <div style="color:cornflowerblue" >
        @Html.DisplayFor(model => model.Status.StatusName)
    </div>
            <h3 style="padding-bottom:5px; border-bottom: solid black 1px;">@Html.DisplayNameFor(model => model.Summary)</h3>

            <div class="display-field">
                @Html.DisplayFor(model => model.Summary)
            </div>*@
            @*<h3>Creator</h3>
            <div class="display-field">
               
            </div>*@
          
            @*<h3>@Html.DisplayNameFor(model => model.Type.TypeName)</h3>

            <div class="display-field">
                @Html.DisplayFor(model => model.Type.TypeName)
            </div>*@
    @*<h3 style="padding-bottom:5px; border-bottom: solid black 1px;">
        Invited Friends
    </h3>
    <table class="table table-bordered">
        @foreach (var item in Model.InvitedUsers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>

            </tr>
        }
    </table>*@



    <h3 style="padding-bottom:5px; border-bottom: solid black 1px;"> Contributions </h3>
            <table class="table table-striped">
                <tr>
                    <th>
                        Friend
                    </th>
                    <th>
                        Type
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Amount
                    </th>


                    <th></th>
                </tr>

                @foreach (var item in Model.Contributions)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type.ContributionTypeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>


                        <td></td>

                    </tr>
                }

            </table>
</fieldset>
<br />
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

3NET_EventManagement/3NET_EventManagement/Views/Event/Index.cshtml
@model IEnumerable<_3NET_EventManagement.Models.Event>

@{
    ViewBag.Title = "My Events";
}

<h2>@ViewBag.Title</h2>
<p style="background-color: #7ce47b; padding: 5px; border-radius:0.5em;"> Indication : you only can invite friend when your event is "Open"</p>
<p style="float:right;">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>

<p> @ViewBag.message </p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creator.UserName) 
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status.StatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type.TypeName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @if(item.Summary.Length > 10)
                {
                    string textTrimmed = item.Summary.Substring(0, 10);
                    @(textTrimmed)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Summary )
                }
          
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creator.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.StatusName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type.TypeName)
            </td>
            <td>

                @if (item.CreatorId == WebSecurity.GetUserId(User.Identity.Name) || Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info btn-sm" })
                }
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })

                @if (item.CreatorId == WebSecurity.GetUserId(User.Identity.Name) || Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                }

                @if (item.CreatorId == WebSecurity.GetUserId(User.Identity.Name) && item.Status.StatusName.Equals("Open"))
                {
                    @Html.ActionLink("Invite Friend", "InviteFriend", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                }

                @if (item.Invitations.Where(x => x.UserId == WebSecurity.GetUserId(User.Identity.Name)).FirstOrDefault() != null)
                {

                    @Html.ActionLink("Add Contribution", "Create", "Contribution", new { id = item.Id }, new { @class="btn btn-info btn-sm" })
                }
                @if (Roles.GetRolesForUser(User.Identity.Name).Contains("admin") && item.Status.StatusName.Equals("Pending"))
                {

                    @Html.ActionLink("UnLock", "LockOrUnlock", "Event", new { id = item.Id }, new { @class="btn btn-success btn-sm" })
                }
                @if (Roles.GetRolesForUser(User.Identity.Name).Contains("admin") && item.Status.StatusName.Equals("Open"))
                {

                    @Html.ActionLink("Lock", "LockOrUnlock", "Event", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                }
                @*|
                    @if(item.InvitedUsers.Where(x => x.Id == WebSecurity.GetUserId(User.Identity.Name)).FirstOrDefault() != null || ViewBag.isOwner == true)
                    {
                        @Html.ActionLink("View Contribution", "Index","Contribution", new { id=item.Id }, null )
                    }*@
            </td>
        </tr>
    }

</table>