3NET_EventManagement/3NET_EventManagement/Controllers/FriendController.cs
using _3NET_EventManagement.Filters;
using _3NET_EventManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace _3NET_EventManagement.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class FriendController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();
        //
        // GET: /Friend/

        public ActionResult Index()
        {
            User user = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));

            return View(user.Friends.ToList());
        }

        //
        // GET: /Friend/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }


        //
        // GET: /Friend/Delete/5
        public ActionResult Delete(int id)
        {

            db.Users.Find(WebSecurity.GetUserId(User.Identity.Name)).Friends.RemoveAt(id);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

        //
        // GET: /Friend/Search

        public ActionResult Search()
        {
           
            return View();
        }

        //
        // GET: /Friend/SearchResults

        public ActionResult SearchResults()
        {

            return View();
        }

        // Action link avec l'action Add
        // GET: /Friend/Add/5
        public ActionResult Add(int id)
        {
            try
            {
               
                User currentUser = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
                User friend = db.Users.Find(id);
                // Lorsqu'on ajoute un ami, on est automatiquement ajouté en tant qu'ami chez la personne en face
                currentUser.Friends.Add(friend);
                if(friend.Friends.Where( x => x.Id == currentUser.Id).FirstOrDefault() == null)
                {
                    friend.Friends.Add(currentUser);
                }
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }

        //
        // POST: /Friend/Search

        [HttpPost]
        public ActionResult Search(AddFriendViewModel addFriendViewModel)
        {
            
                if (!ModelState.IsValid) return View();
                // On recherche les amis selon l username , le nom et le prenom
                List<User> friends =  (from u in db.Users
                                            where u.UserName.Contains(addFriendViewModel.FriendName) || u.Name.Contains(addFriendViewModel.FriendName) || u.LastName.Contains(addFriendViewModel.FriendName)
                                            select u).ToList();

             
                User currentUser = db.Users.Find(WebSecurity.GetUserId(User.Identity.Name));
              
                if (friends.Count() == 0)
                {
                    // Si l'utilisateur n 'existe pas 
                    ViewData["error"] = " User not found, please try other username.";
                    return View();
                }
                List<User> filteredFriends = new List<User>();
                List<User> listOfFriends = currentUser.Friends.ToList();
                foreach(User item in friends)
                {
                   // Si ce n'est pas l'utilisateur connecté
                    if (item.Id != currentUser.Id)
                    {
                     filteredFriends.Add(item);  
                    }
                    // On récupère et filtre par rapport aux amis déjà ajoutés
                    foreach (var friend in listOfFriends)
                    {
                        if (friend.Id == item.Id)
                        {
                            filteredFriends.Remove(item);
                        }
                    }
                   
                       
                }
                if (filteredFriends.Count == 0)
                {
                    ViewData["error"] = " User not found, please try other username.";
                    return View();
                }

                
                return View("SearchResults", filteredFriends.ToList());
            
        }

        //
        // GET: /Friend/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Friend/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

3NET_EventManagement/3NET_EventManagement/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3NET_EventManagement.Models;
using WebMatrix.WebData;
using Microsoft.Web.WebPages.OAuth;
using System.Web.Security;

namespace _3NET_EventManagement.Controllers
{
    public class UserController : Controller
    {
        private AppDbContext db = new AppDbContext();

        //
        // GET: /User/

        public ActionResult Index()
        {
            if (!Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                return HttpNotFound();
            if (TempData["createdUser"] != null)
            {
                ViewData["createdUser"] = TempData["createdUser"].ToString();
            }
            List<User> listOfUsers = new List<User>();
            // On filtre pour afficher que les utilisateurs voulus
            foreach(var item in db.Users.ToList())
            {
                if ( item != db.Users.Find(WebSecurity.GetUserId(User.Identity.Name)))
                {
                    listOfUsers.Add(item);
                }
            }

            return View(listOfUsers);
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(int id = 0)
        {
            if (!Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                return HttpNotFound();
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            if (!Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                return HttpNotFound();
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                if (db.Users.Where(x => x.UserName == user.UserName).FirstOrDefault() == null)
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    WebSecurity.CreateUserAndAccount(user.UserName, "123456");
                    // si la checkbox admin est cochée ou pas on le met en tant qu'admin ou pas.
                    if (user.isAdmin == false)
                    {
                        Roles.AddUserToRole(user.UserName, "user");
                        TempData["createdUser"] = "User created with default password '123456', please contact him to give the password";
                    }
                    else
                    {
                        Roles.AddUserToRole(user.UserName, "admin");
                        TempData["createdUser"] = "User admin created with default password '123456', please contact him to give the password";
                    }
                     
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["error"] = "Username already exists please choose another.";
                }

                
            }

            return View(user);
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                return HttpNotFound();
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
                return HttpNotFound();
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);

            foreach(var item in user.Friends)
            {
                var userFriend = db.Users.Find(item.Id);
                userFriend.Friends.Remove(user);
            }
            user.Friends.Clear();
            
            var listOfInvitations = db.Invitations.Where(x => x.UserId == id).ToList();
            foreach (var item in listOfInvitations)
                db.Invitations.Remove(item);
            var listOfContributions = db.Contributions.Where(x => x.UserId == id).ToList();
            foreach (var item in listOfContributions)
                db.Contributions.Remove(item);

            db.Users.Remove(user);
            db.SaveChanges();
            
            ((SimpleMembershipProvider)Membership.Provider).DeleteAccount(user.UserName); // deletes record from webpages_Membership table
            Roles.RemoveUserFromRole(user.UserName, Roles.GetRolesForUser(user.Name).First());
            ((SimpleMembershipProvider)Membership.Provider).DeleteUser(user.UserName, true);
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

3NET_EventManagement/3NET_EventManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Synchronic World</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
       
        @Styles.Render("~/Content/css")
        <link rel="stylesheet" href="/Content/bootstrap.min.css" type="text/css" />
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Synchronic World", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>

@if (Request.IsAuthenticated && Roles.GetRolesForUser(User.Identity.Name).Contains("admin"))
{
     <ul id="menu">
                            <li>@Html.ActionLink("Modify Password", "Manage", "Account")</li>
                            <li>@Html.ActionLink("Edit Profil", "Edit", "Account")</li>
                             <li>@Html.ActionLink("View Users", "Index", "User")</li>
                            <li>@Html.ActionLink("View Events", "Index", "Event")</li>
                            <li>@Html.ActionLink("View Friends", "Index", "Friend")</li>
                            
                        </ul>
}
else 
if (Request.IsAuthenticated)
{
                        <ul id="menu">
                            <li>@Html.ActionLink("Modify Password", "Manage", "Account")</li>
                            <li>@Html.ActionLink("Edit Profil", "Edit", "Account")</li>
                            <li>@Html.ActionLink("View Events", "Index", "Event")</li>
                            <li>@Html.ActionLink("View Friends", "Index", "Friend")</li>
                            
                        </ul>
}else
{ 
                    <nav>
                        <ul id="menu">
                            @*<li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        </ul>
                    </nav>
                    }
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My Application ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>